name: Release Process

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        
      - name: Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Create Release Issue
        id: create_issue
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/issues
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          title: "Release ${{ github.ref }}"
          body: |
            Release Author: ${{ github.actor }}
            Release Date: ${{ github.event.commits[0].timestamp }}
            Version: ${{ github.ref }}
            Changelog: ${{ steps.changelog.outputs.changelog }}
            Test results: [Link to test results](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          labels: RELEASE
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Publish to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          publish_dir: ./public

      - name: Update Release Issue
        id: update_issue
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/issues/{issue_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          issue_number: ${{ fromJson(steps.create_issue.outputs.data).number }}
          body: |
            Release Author: ${{ github.actor }}
            Release Date: ${{ github.event.commits[0].timestamp }}
            Version: ${{ github.ref }}
            Changelog: ${{ steps.changelog.outputs.changelog }}
            Test results: [Link to test results](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            Deployment: [Link to deployment](https://${{ github.repository_owner }}.github.io/${{ github.repository }})
          state: closed
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
