name: Release Process

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Create Release Branch
        run: |
          git checkout -b "Release-${{ github.ref_name }}"
          git push origin "Release-${{ github.ref_name }}"

      - name: Get current and previous tags
        id: tags
        run: |
          echo "::set-output name=current::$(git describe --tags --abbrev=0)"
          echo "::set-output name=previous::$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))"
        shell: bash

      - name: Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.RELEASE_TOKEN }}
          head-ref: ${{ steps.tags.outputs.current }}
          base-ref: ${{ steps.tags.outputs.previous }}

      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Check if Release Issue exists
        id: check_issue
        uses: octokit/graphql-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          query: |
            query($owner: String!, $repo: String!, $tagName: String!) {
              repository(owner: $owner, name: $repo) {
                issue(number: $tagName) {
                  number
                  body
                }
              }
            }
          variables: |
            {
              "owner": "${{ github.repository_owner }}",
              "repo": "${{ github.event.repository.name }}",
              "tagName": "${{ github.ref_name }}"
            }

      - name: Set ISSUE_BODY and ISSUE_NUMBER environment variables
        run: |
          echo "ISSUE_BODY=${{ fromJson(steps.check_issue.outputs.data).repository.issue.body }}" >> $GITHUB_ENV
          echo "ISSUE_NUMBER=${{ fromJson(steps.check_issue.outputs.data).repository.issue.number }}" >> $GITHUB_ENV

      - name: Create Release Issue
        if: env.ISSUE_NUMBER == null
        id: create_issue
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/issues
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          title: "Release ${{ github.ref_name }}"
          body: ${{ toJSON(env.REQUEST_BODY) }}
          labels: '["RELEASE"]'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          REQUEST_BODY: |
            Release Author: ${{ github.actor }}
            Release Date: ${{ env.CURRENT_DATE }}
            Version: ${{ github.ref_name }}
            Changelog: ${{ steps.changelog.outputs.changelog }}

      - name: Set ISSUE_NUMBER after creation
        if: env.ISSUE_NUMBER == null
        run: |
          echo "ISSUE_NUMBER=${{ fromJson(steps.create_issue.outputs.data).number }}" >> $GITHUB_ENV

      - name: Run module tests
        run: npm run test-ci
        continue-on-error: false

      - name: Run e2e tests with retries
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 3
          retry_on: timeout
          command: npm run e2e-ci

      - name: Update Release Issue
        if: env.ISSUE_NUMBER != null
        id: update_issue
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/issues/{issue_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ env.ISSUE_NUMBER }}
          body: ${{ toJSON(env.REQUEST_BODY) }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          REQUEST_BODY: |
            ${{ env.ISSUE_BODY }}
            Test results: [Link to test results](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Build
        run: npm run build

      - name: Publish to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          publish_dir: ./build

      - name: Close Release Issue
        id: close_issue
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/issues/{issue_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ fromJson(steps.create_issue.outputs.data).number }}
          state: closed
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
