name: Release Process

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

        
      - name: Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.RELEASE_TOKEN }}

      - name: Create Release Issue
        id: create_issue
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/issues
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          title: "Release ${{ github.ref_name }}"
          body: ${{ toJSON(env.REQUEST_BODY) }}
          labels: '["RELEASE"]'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          REQUEST_BODY: |
            Release Author: ${{ github.actor }}
            Release Date: ${{ github.event.commits[0].timestamp }}
            Version: ${{ github.ref_name }}
            Changelog: ${{ steps.changelog.outputs.changelog }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test-ci
        continue-on-error: false

      - name: Update Release Issue
        id: update_issue
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/issues/{issue_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ fromJson(steps.create_issue.outputs.data).number }}
          body: ${{ toJSON(env.REQUEST_BODY) }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          REQUEST_BODY: |
            ${{ fromJson(steps.create_issue.outputs.data).body }}
            Test results: [Link to test results](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Publish to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          publish_dir: ./public

      - name: Close Release Issue
        id: close_issue
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/issues/{issue_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ fromJson(steps.create_issue.outputs.data).number }}
          state: closed
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
