name: SHRI-CI
run-name: ${{ github.actor }} is starting tests 🚀
on: pull_request_target
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install packages
        run: npm ci

      - name: run tests
        run: npm run test-ci